version: '{build}'
os: Visual Studio 2015

configuration:
    - Debug 
    - Release

platform: x86

clone_depth: 1

build:
  parallel: true
  project: YSF.sln
  
artifacts:
    - path: YSFCompiled.zip
      name: YSF Plugin
